name: taskd_setup
description: A new Flutter project.

publish_to: 'none'

version: 0.0.0-alpha.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  taskc:
    git:
      url: https://github.com/bradyt/taskd-client-dart.git

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test:

flutter:
  assets:
    - fixture/.task/
    - fixture/.taskrc

  uses-material-design: true
