name: flutter drive
on: [push, pull_request]
jobs:
  drive:
    strategy:
      matrix:
        device:
        - "pixel"
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'

    # install taskwarrior and taskd
    - run: sudo touch /etc/apt/sources.list.d/bionic.list
    - run: echo 'deb http://archive.ubuntu.com/ubuntu/ bionic universe\n# deb-src http://archive.ubuntu.com/ubuntu/ bionic universe\ndeb http://archive.ubuntu.com/ubuntu/ bionic-updates universe\n# deb-src http://archive.ubuntu.com/ubuntu/ bionic-updates universe' | sudo tee -a /etc/apt/sources.list.d/bionic.list
    - run: sudo apt-get update && sudo apt-get install -y taskwarrior taskd

    - uses: subosito/flutter-action@v1

    # toc: https://taskwarrior.org/docs/taskserver/setup.html
    - run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
    - run: dart pub global activate --source git https://github.com/bradyt/taskd-setup-dart.git
    - run: taskd-setup --CN=10.0.2.2 --address=127.0.0.1
      working-directory: fixture

    - run: TASKDDATA='fixture/var/taskd' taskdctl start

    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        profile: ${{ matrix.device }}
        script: |
          flutter pub get
          flutter drive --target=test_driver/app.dart
